FROM n8nio/n8n:latest
WORKDIR /usr/src/app
RUN npm install -g n8n
COPY . .
EXPOSE 5678
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=$PORT
ENV NBN_RUNNERS_ENABLED=true
ENV N8N_DB_TYPE=postgresdb
ENV N8N_DB_POSTGRESDB_HOST=dpg-d0aq73h5pdvs73c1p7og-a
ENV N8N_DB_POSTGRESDB_PORT=5432
ENV N8N_DB_POSTGRESDB_DATABASE=n8n_db_lcjb
ENV N8N_DB_POSTGRESDB_USER=n8n_db_lcjb_user
ENV N8N_DB_POSTGRESDB_PASSWORD=enFgEGSHOBpQPLSCSmhFXC97f00ukd3C
CMD ["n8n", "start"]
